### ISSUE TITLE
Adding a Readme file about the program and benefits

### ISSUE THREAD

**Issue by saiyam1814** [kubesimplify/ambassadors#2]
This is important as we are scaling out.

**Comment by abh139** [comment]
@saiyam1814 I wanna work on this.

**Comment by BushraNazish** [comment]
> This is important as we are scaling out.

I would like to work on it.

**Comment by Arnav-Barman** [comment]
Can I help out in making it?

**Comment by bhavyastar** [comment]
> This is important as we are scaling out.

I would like to work on it. Can you please assign this to me?

**Comment by Abhishekvrt** [comment]
We all want to work on this PR and this community. First we have to know what is this program so one or team can make this repo alive and add all the necessary resources here.

**Comment by saiyam1814** [comment]
This is completed !
